### ISSUE TITLE
Event for open/close state

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-toast#10]
For example, 0.5 fired `core-overlay-open` when the toast opened. It would be nice to have events fired when the toast opens/closes so users can latch onto them. My use case is kicking off other animations once the toast comes up.

**Comment by cdata** [comment]
`paper-toast` needs to be adapted to use `iron-overlay-behavior`, at which point the event dispatch will be inherited.

**Comment by enguyen** [comment]
Having `paper-toast` use `iron-overlay-behavior` would also fix another issue, wherein an existing overlay element (e.g. `paper-dialog`) with a backdrop opens a toast. In this case, the toast will appear beneath the backdrop and be very difficult to read.

**Comment by dsschnau** [comment]
+1

**Comment by Zippersk** [comment]
I
