### ISSUE TITLE
Hide then show toast

### ISSUE THREAD

**Issue by yebrahim** [PolymerElements/paper-toast#100]
If I want to show a new toast message while one is shown on the screen, I would like to animate the dismissal of any toast before showing a new one. If I call `hide` then `show` immediately, the animation does not trigger, and the user ends up seeing just the text changing across the two messages.

**Comment by web-padawan** [comment]
You can call `hide` and then use `this.async` to invoke `show` there, it worked for me.

**Comment by yebrahim** [comment]
Is this what you mean:
```
toast.hide();
toast.async(() => toast.show());
```
This didn't make any difference for me. Can you share an example?

**Comment by valdrinkoshi** [comment]
If you want to wait for all toasts to be closed before opening a new one, you can listen for `iron-overlay-closed` event on the closing toast, and then open the toast you want to open 👌

**Comment by yebrahim** [comment]
I was looking for a way to hide it immediately (with animation), then open the new one.

**Comment by valdrinkoshi** [comment]
Then you should be able to use the snippet in my previous comment to achieve that 👌  
Here a more generic solution in case you don't have access to `closingToast`:
```js

runAfterClosingOverlay(getCurrentOverlay('paper-toast'), function() {
  // setup myToast, then open it.
  myToast.opened = true;
});

function getCurrentOverlay(type) {
  // get the last opened overlay from the overlay manager.
  const overlay = Polymer.IronOverlayManager.currentOverlay();
  if (overlay && overlay.localName === type) {
    return overlay;
  }
}

function runAfterClosingOverlay(closingOverlay, callback) {
  if (!closingOverlay) {
    callback();
  } else {
    // ensure it is closed.
    closingOverlay.opened = false;
    // Listen once for the event.
    closingOverlay.addEventListener('iron-overlay-closed', function onClosed() {
      closingOverlay.removeEventListener('iron-overlay-closed', onClosed);
      callback();
    });
  }
}
