### ISSUE TITLE
open() close() etc. methods

### ISSUE THREAD

**Issue by timreichen** [PolymerElements/paper-toast#103]
I saw the [presentation](https://www.youtube.com/watch?v=iJ9hS54BRag) and around the 11. minute Rob Dodson explains that methods like open() and close() should be avoided and an attribute (which paper-toast already has) should be used for it. I guess this is not the only element that has these kind of methods.
My question is, are you going to drop these methods since it is in contradiction of what he said? His explanation seemed logical to me and it would make sense to do it for the next big release (e.g. Polymer 3.0)

Thank you for your answer

**Comment by valdrinkoshi** [comment]
The 3.0 release will be a mechanical conversion of the existing implementation, moving from HTML Imports to JavaScript modules and from Bower to NPM; we won't make any other changes in this process. Our post-3.0 plan is to collaborate with the Material Design Components team on a new set of Material Design web components, which will be based on the new Material Design 2 specs and closely track updates to the specs over time. We'll have more to say about this at Google I/O in May.
