### ISSUE TITLE
toast will appear briefly before quickly hiding on page load in Firefox

### ISSUE THREAD

**Issue by triune** [PolymerElements/paper-toast#11]
This is an issue with 1.0 and was not an issue with 0.5

See: 
http://localhost/components/paper-toast/demo/index.html

**Comment by cnbuff410** [comment]
We see the same issue here. Our current workaround is to make toast invisible and have a 1 second timer to make it visible afterwards. Pretty dirty I would say. Hopefully this issue will be solved soon.
