### ISSUE TITLE
toast no longer visible during modal dialog

### ISSUE THREAD

**Issue by triune** [PolymerElements/paper-toast#12]
In 0.5, using a paper-action-dialog that was configured to be modal, a toast would appear above the modal backdrop so the toast was readable. In 1.0 however, the toast will appear below the modal backdrop making it unreadable; in this case we are using paper-dialog (modal). I believe a toast should be visible in this case since it may be an error message resulting from the action the user performed in the dialog.

**Comment by valdrinkoshi** [comment]
This has been fixed by #36
