### ISSUE TITLE
paper-toast ignores "visible" property

### ISSUE THREAD

**Issue by eximius313** [PolymerElements/paper-toast#13]
although "visible" is set to "true", paper-toast is not showing up.
one has to manually invoke ```document.getElementById('myToast').show();```

**Comment by cdata** [comment]
Thanks, this is a bug. We'll take a look.

**Comment by Whytey** [comment]
Actually, the docs state that 'visible' is a read-only property.  That said, I would prefer if it honoured this setting, which would allow you to use it with, for example, the iron-ajax 'loading' property.

**Comment by eximius313** [comment]
I don't want to manipulate ```visible``` property. 
I want the toast to be already opened when the page loads and ```visible``` flag is initially set to true

**Comment by valdrinkoshi** [comment]
Please use the property `opened` instead of `visible`

**Comment by eximius313** [comment]
But according to the documentation (https://elements.polymer-project.org/elements/paper-toast), there is no ```opened``` property...

**Comment by valdrinkoshi** [comment]
It got introduced in `v1.1.0` (by this PR #36). 
We'll update soon https://elements.polymer-project.org/elements/paper-toast to use the latest version
