### ISSUE TITLE
 Bug with hide() paper-toast

### ISSUE THREAD

**Issue by tdesc** [PolymerElements/paper-toast#16]
During paper-toast shown on screen hide() do nothing.

**Comment by ebidel** [comment]
Do you have a test that repos this bug? I cannot reproduce it.

**Comment by pepperlk** [comment]
I also have this.. The toast will show but not hide on hide() method

Toas is inside a template element. Will try to add more info.

**Comment by valdrinkoshi** [comment]
tested with v1.1.1, and could not reproduce it. Closing this, please feel free to open it again with more details on how to reproduce it.
