### ISSUE TITLE
Toast no longer fits to bottom on mobile screen

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-toast#17]
The `fit-bottom` class is no longer applied. We lost the responsiveness in the port:

![screen shot 2015-07-01 at 9 08 51 am](https://cloud.githubusercontent.com/assets/238208/8459288/0744e42a-1fd1-11e5-86f1-8f3299c64607.png)

We should put this back so the toast adheres to the MD spec and works well on mobile.

**Comment by valdrinkoshi** [comment]
verified and could not reproduce the issue, toast is correctly displayed fitting the bottom (`fit-bottom` class is applied)
http://jsbin.com/wapofeharu/edit?html,output
![screen shot 2015-11-17 at 6 32 25 pm](https://cloud.githubusercontent.com/assets/6173664/11231038/97a36ab4-8d59-11e5-8c4d-6d5813e0aef3.png)

Nevertheless we should update the demo page to show the functionality
