### ISSUE TITLE
Add --paper-toast CSS variable

### ISSUE THREAD

**Issue by agektmr** [PolymerElements/paper-toast#18]
There's no way to style this element from outside of element. Please add `--paper-toast` CSS variable.

**Comment by tostrowski** [comment]
+1, I would like to use it as success/error message. Would be great if I could customize background and font color.

**Comment by pensierinmusica** [comment]
+1 agree with @tostrowski 

For example, in an app I'm currently working on, the lower part of the screen is black and the toast box becomes invisible. CSS `background color` and `color` should be customizable.
