### ISSUE TITLE
How to get notified when the toast is hidden?

### ISSUE THREAD

**Issue by Mygod** [PolymerElements/paper-toast#19]
Having an event or add `notify: true` to `visible` would sure help with this...

**Comment by leodido** [comment]
:+1:

**Comment by leodido** [comment]
Currently there is no way why:
1. `visible` property does not have `notify: true`
2. it does not use `IronOverlayBehavior` (which `opened` property has `notify: true` making elements that uses it capable of listening its changes)

Actually I temporarily solved this issue with a `MutationObserver`, observing the changes to the `class` attribute. Follows ES6 code.

```es6
const observerConfig = { attributes: true };
const observer = new MutationObserver((mutations) => {
  mutations.forEach((mutation) => {
    if (mutation.attributeName === 'class') {
      console.log(mutation.target.visible);
    }
  });
});
observer.observe(toast, observerConfig);
observer.disconnect();
```
