### ISSUE TITLE
Microsoft Edge doesn't understand "show()" method

### ISSUE THREAD

**Issue by Zippersk** [PolymerElements/paper-toast#20]
My code: 

    <?php if( !empty( $error )){ ?>
	   <paper-toast id="Toasteror" text="<?php echo $error; ?>"></paper-toast>
	   <script>document.querySelector('#Toasteror').show();</script>
    <?php } ?>

what MS Edge says:
![snimka](https://cloud.githubusercontent.com/assets/6651236/9329260/698e3f78-45b0-11e5-936f-293161cbdfd6.PNG)

In chrome and other browsers it works fine. This error only occurs in MS Edge.

I have to import jQuery to show toast in all browsers?

**Comment by valdrinkoshi** [comment]
Hi @Zippersk, 
I recommend to set the `visible` property of the `paper-toast` (there is a bug on that #13 currently being fixed)
```html
<paper-toast visible text="<?php echo $error; ?>"></paper-toast>
```

Here some other temporary solutions until that #13 is not merged on master:
- move js code in a file & use html import in your html page
- listen to the event `HTMLImportsLoaded` before executing your code
```html
<script>
document.addEventListener('HTMLImportsLoaded', function() {
  document.querySelector('#Toasteror').show();
});
</script>
