### ISSUE TITLE
Demo Safari Error

### ISSUE THREAD

**Issue by ixchelruiz** [PolymerElements/paper-toast#29]
On Safari Version 9.0 (11601.1.56)
I have the following error
TypeError: document.querySelector('#toast2').show is not a function. (In 'document.querySelector('#toast2').show()', 'document.querySelector('#toast2').show' is undefined)

**Comment by valdrinkoshi** [comment]
Hi @ixchelruiz, could you please provide more details about when the script is performed? e.g. is it done like in your index.html?
This might be related to the fact that safari doesn't support yet HTML Imports, so there are couple of solutions to overcome this issue. See more details here https://github.com/PolymerElements/paper-toast/issues/20#issuecomment-157210058
