### ISSUE TITLE
prefix content for toast

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/paper-toast#40]
With `paper-toast`, we could have some prefix content that precedes the text.

### Option 1

One way would be to have `prefix` attribute on the children, in order for `paper-toast` to lay the content in the right order:
```html
<paper-toast text="Error!">
   <iron-icon icon="error-outline" prefix></iron-icon>
</paper-toast>
```

### Option 2

Another option is to avoid setting `text` and just adding the content in the desired order:
```html
<paper-toast>
  <iron-icon icon="error-outline"></iron-icon>
  <span>Error!</span>
</paper-toast>
```

**Comment by valdrinkoshi** [comment]
Considering that:
- the Paper design specs strictly prohibit having icons within the toast message
https://www.google.com/design/spec/components/snackbars-toasts.html#snackbars-toasts-usage
- less selectors within `paper-toast` means better performance

I would vote for the former option

**Comment by valdrinkoshi** [comment]
@cdata @honzalo FYI

**Comment by honzalo** [comment]
I would vote for Option 2, it's a more flexible solution. Nonetheless, given that Material Design specs clearly state toasts cannot contain icons I would opt for leaving this functionality out of the paper-toast official repository.

**Comment by valdrinkoshi** [comment]
We're on the same page :) Closing this issue then
