### ISSUE TITLE
Example source missing from the documentation page

### ISSUE THREAD

**Issue by adamos42** [PolymerElements/paper-toast#41]
On the https://elements.polymer-project.org/elements/paper-toast site the documentation missing an example usage source like the other elements has. Please add something like this:

```
<paper-toast id="example_toast" text="Some message in toast!"></paper-toast>

<script>
    document.getElementById('example_toast').show();
</script>
```

**Comment by valdrinkoshi** [comment]
Hi @adamos42, the demo page source code could be used as example https://elements.polymer-project.org/elements/paper-toast?view=demo:demo/index.html&active=paper-toast

Nevertheless, the documentation needs to be enhanced.

**Comment by adamos42** [comment]
@valdrinkoshi I did used that, but after I implemented 10-12 element in my project I expected an example on the "Docs" page :)

**Comment by valdrinkoshi** [comment]
Yep! coming with PR #39
