### ISSUE TITLE
1.1.0 throws console errors

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-toast#43]
https://github.com/PolymerElements/paper-toast/commit/b220515518e07b31931ef50a59ce19467fef9bd2#diff-5eaf4a828ce41e17d9bf6032480c426cR151

Is breaking our Google Developers Codelab frontend.  When `opened === false`, `PaperToast.currentToast` does not exist yet.

![screen shot 2015-11-25 at 2 24 03 pm](https://cloud.githubusercontent.com/assets/238208/11410911/326287ac-9380-11e5-8215-450567e151d8.png)

**Comment by ebidel** [comment]
Btw, this happens when using async imports (`async` on our main page import).

**Comment by valdrinkoshi** [comment]
Thanks for the catch @ebidel! Being fixed in #42
