### ISSUE TITLE
1.1.1 release

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-toast#44]
@valdrinkoshi would you mind doing a 1.1.1 release with the updates from https://github.com/PolymerElements/paper-toast/commit/4b1e7fdbb4b8b9095b66580e4a760ed07b266277?

**Comment by fiws** [comment]
+1

**Comment by valdrinkoshi** [comment]
Sure, I'd like to wait for PR#39 to be reviewed and merged before I do it though, this should happen today

**Comment by valdrinkoshi** [comment]
Done https://github.com/PolymerElements/paper-toast/releases/tag/v1.1.1
