### ISSUE TITLE
PaperToast not working with Dart (in Chrome/Dartium?)

### ISSUE THREAD

**Issue by lymp** [PolymerElements/paper-toast#47]
PaperToast not showing at all in Dart. Posting here following this post:

https://groups.google.com/a/dartlang.org/forum/#!topic/web/qGQOwa6HvUU

Tried this, but still no luck:

void test() {
     PaperToast   toast=new PaperToast();
     toast.text='hello';
     toast.async(() { toast.show(); });
}

**Comment by valdrinkoshi** [comment]
Hi @lymp, with `paper-toast` [v1.1.1](https://github.com/PolymerElements/paper-toast/releases/tag/v1.1.1) you can do any of the following: 

```dart
// either
toast.opened = true;
// or
toast.open();
// or
toast.show();
```

Hope it helps, feel free to reopen if you keep facing issues on this
