### ISSUE TITLE
Single-line toast message not vertically centered

### ISSUE THREAD

**Issue by jasongardnerlv** [PolymerElements/paper-toast#51]
I'm curious why the padding is set to:

padding: 16px 24px 12px;

when the Material Design spec shows single-line toasts have a top and bottom spacing of 14 for each.

https://www.google.com/design/spec/components/snackbars-toasts.html#snackbars-toasts-specs

**Comment by valdrinkoshi** [comment]
Hi @jasongardnerlv, you're right `paper-toast` should have `padding: 16px 24px`.
Currently it works anyways because we set the `min-height: 48px`, which compensates for those 4 missing pixels.

**Comment by valdrinkoshi** [comment]
When we have multi-line messages though we can see that the bottom padding is less than the top padding.
@notwaldorf do you have more info on why the padding was set with these values?

**Comment by WoodyWoodsta** [comment]
Yep, adding a `paper-button` to the content of the toast makes the incorrect padding apparent:

![screenshot from 2016-01-06 00 00 14](https://cloud.githubusercontent.com/assets/8268040/12128836/851dd822-b408-11e5-9eed-ce3f6b08c078.png)
