### ISSUE TITLE
Should be able to swipe off screen

### ISSUE THREAD

**Issue by frankiefu** [PolymerElements/paper-toast#6]
0.5 paper-toast allows user to swipe the toast off screen.  We need to support the same in 1.0.

**Comment by notwaldorf** [comment]
Great idea @frankiefu :)

**Comment by valdrinkoshi** [comment]
This could be achieved by wrapping the `paper-toasts` in a `iron-swipeable-container`.

**Comment by abdonrd** [comment]
I think that would be awesome if the `iron-swipeable-container` exposes an `IronSwipeableBehavior`. :)

Then we can have an property in the `paper-toast` for have the swipe.

**Comment by MeTaNoV** [comment]
+1 seems legit and logical

**Comment by notwaldorf** [comment]
I'm not sure I understand why this would help `paper-toast`. Swiping is an action that happens inside a container; it's not an attribute of an element. The goal of `iron-swipeable-container` is to allow swiping of anything in it. If you want `paper-toast` to be swipeable, you need to put it in a container that allows this. Adding the `IronSwipeableBeahviour` to `paper-toast` would be an anti-pattern, in my opinion
