### ISSUE TITLE
Proposed method: showText()

### ISSUE THREAD

**Issue by redbassett** [PolymerElements/paper-toast#61]
As noted in #50, this is a proposal to add an alias method `showText()` that combines commonly used lines of code:

```javascript
myToast.text = "Hello World!";
myToast.show();
```
```javascript
myToast.showText("Hello World!");
```

This method would serve to reduce the need to use the two lines in the former snippet in conjunction, especially if the setting and immediate showing of text in a `<paper-toast>` element is a common action across an app or component.

**Comment by valdrinkoshi** [comment]
What if instead we have a config object passed to `show` method?
Something like:
```javascript
myToast.show({
  text: "Hello World",
  duration: 3000
});
```
The toast will either set the new values or keep the old ones, and open the toast right after

**Comment by redbassett** [comment]
I like that idea!

**Comment by valdrinkoshi** [comment]
@redbassett feel free to open a PR for this if you feel like it :)

**Comment by redbassett** [comment]
I'll likely open a new PR if I get the code up and running, as the old PR linked above is kinda useless code.
