### ISSUE TITLE
Need summary docs

### ISSUE THREAD

**Issue by frankiefu** [PolymerElements/paper-toast#7]
No docs at all here: https://github.com/PolymerElements/paper-toast/blob/56ff0143cf409a81d505dfa744f713dee68c5647/paper-toast.html

**Comment by ebidel** [comment]
The docs at https://elements.polymer-project.org/elements/paper-toast also do not mention `iron-announce` is fired

**Comment by notwaldorf** [comment]
apply label: documentation
