### ISSUE TITLE
paper-toast's alignment abilities is a lie.

### ISSUE THREAD

**Issue by lozandier** [PolymerElements/paper-toast#75]
### Description
As though it's become possessed by GLaDOs, the alignment abilities of `paper-toast` is a lie. 

As informed by a colleague getting into Polymer & attempting to rehabilitate it to work probably in vain during a debugging session, its ability to align seems to be failing while `paper-dialog` used in the same exact ways (& same align properties) does not fail. 

Accordingly, its inheritance of overlay behavior & so on seems to be leading it astray to the extent it's betraying its consumers that is compounded that the common logical step of using `paper-dialog` to test its alignment shows it seems `paper-toast` has indeed lost its way in the art of aligning itself as its owner bids.

Its lies led us no choice but for `paper-dialog` to show it how being a material design toast is done.

### Expected outcome
![Happy Toasting Time](https://wordsthroughtheglass.files.wordpress.com/2012/05/toaster.gif?w=538)
1. When `fitInto`, `horizontalAlign`, &/or `vertialAlignment` is used, it goes where it ought to go as its `parentElement` bids
- `node.horizontalAlign ="left|right"` goes left/right
- `node.verticalAlign ="top|bottom"` goes top/bottom
- `node.horizontalAlign="auto"` === centered
- `node.verticalAlign="auto"`=== centered
- `"node.fitInto="someID"` === the toast fits into `someID`

### Actual outcome
![Bad Time Toasting :(](http://i.imgur.com/8KuCGUY.gif)
`paper-toast` lies.

### Live Demo
http://codepen.io/lozandier/pen/e0f4f64c0cac7aad0ce3b2a71ef47388

### Steps to reproduce
It's such a liar, attempt to use any of the alignment properties (`fitInto`, `horizontalAlign`, `vertialAlign`) and it leads end users astray. Its lies is only matched by GLaDOs & Game of Throne's Cersei before her walk of shame. 

See this issue's expected outcome section to be on the same page of what I thought thee & fellow developer was promised when using it. 

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

### Recommended Reviewers
Last 5 contributors to this repo
- @valdrinkoshi 
- @notwaldorf 
- @abdonrd 
- @azakus 
- @rictic

**Comment by valdrinkoshi** [comment]
Hi @lozandier 
`paper-toast` alignment abilities is not a lie, you just have to use it right:
- have a look at how to use [polygit.org](http://polygit.org), you should point to paper-toast master branch -> polygit.org/**paper-toast+:master**/components/
- [`fitInto`](https://elements.polymer-project.org/elements/iron-fit-behavior#property-fitInto) must be an HTMLElement, not a string (you passed an id of an element that is not in the `document` root, but inside the `x-test` root, hence `document.getElementById('section')` won't work) -> set it on ready, or bind it to a private `x-test` property (whatever is more convenient for you)
- [`verticalOffset`](https://elements.polymer-project.org/elements/iron-fit-behavior#property-verticalOffset) must be a number, not a string (`s/10vh/10`); it is the same as setting margin-top/margin-bottom in css
- <code>s/vertialAlign/verti**c**alAlign</code>
- <code>s/vertialOffset/verti**c**alOffset</code>

Here you go http://jsbin.com/nehejo/2/edit?html,output

**Comment by valdrinkoshi** [comment]
FYI, published `v1.3.0`, so no need to point to the master branch

**Comment by lozandier** [comment]
@valdrinkoshi  Epic use of emojis .

Terrible typos & misuses on my part trying to recreate the issues (including the `fitInto` part that was an error with my example, but was correctly referencing an actual element programmatically prior to spending time creating an isolated use case from my colleague's futile efforts).

There's still confusing behavior I wouldn't mind for you to clear-up that I and my colleague whose code lead me to write this issue: 
1. If setting `verticalOffsest` is the same as setting margin-top/margin-bottom in *CSS*, why can't units be used like `vh` or I'm misunderstanding that statement? I'm of the opinion that statement assumes that the string be scrutinized by methods not enabling consumers to specify the units they find most useful. 

2. While knowing (but somehow forgetting in my glee of having an real world  opportunity to use "The Cake Is Lie" meme for a Github issue) `fitInto` accepting an element node (`HTMLElement`) , wouldn't there be value for `fitInto` to accommodate being used programmatically & declaratively by accepting an element node OR a string? The string can be handled with logic like `(typeof param === 'string')…`this.parentElement.querySelector(query) || document.currentScript.ownerDocument.querySelector('query');`

I'd happily do a PR for that.

**Comment by valdrinkoshi** [comment]
Hi @lozandier
- `verticalOffset, horizontalOffset, verticalAlign, horizontalAlign` were previously properties of `iron-dropdown`, I moved them to `iron-fit-behavior` so that all overlays can benefit from them. `verticalOffset, horizontalOffset` in particular was kept so that in order not to make a breaking change, but ideally they should be deprecated/removed in favor of just using margins in CSS. That said, I believe it might be possible to accept a css value, feel free to give it a shot https://github.com/PolymerElements/iron-fit-behavior/blob/master/iron-fit-behavior.html#L286
- About `fitInto` accepting a string, that could be a great enhancement!

Could you open an issue for each in https://github.com/PolymerElements/iron-fit-behavior/ & do the PR there please? 🍰 

Closing this

**Comment by lozandier** [comment]
Understood, thanks for the thorough response to this, @valdrinkoshi; have a splendid weekend.
