### ISSUE TITLE
Pattern to create multiple toast

### ISSUE THREAD

**Issue by NicolasRannou** [PolymerElements/paper-toast#81]
I would like to have several toast display on top of each other.

Right now if I create 2 toasts and show them, the first toast get hidden by the second toast.

What I would like it the second toast to push the existing toast up.
![screen shot 2016-07-19 at 2 45 34 pm](https://cloud.githubusercontent.com/assets/214063/16950249/a446c9f6-4dbf-11e6-8b20-dfed2a218979.png)

Ideally my toast should also be able to push a fab button up too (like in inbox).
Is such behavior supported?

**Comment by valdrinkoshi** [comment]
Hi @NicolasRannou, this behavior is by design, as mentioned in the Material design: [Snackbars & toasts](https://material.google.com/components/snackbars-toasts.html):
>Show only one snackbar on screen at a time.

**Comment by valdrinkoshi** [comment]
You could pile the messages rather than the toasts, e.g. http://jsbin.com/cuvova/1/edit?html,output
