### ISSUE TITLE
feature request: add ability to show svg images

### ISSUE THREAD

**Issue by triune** [PolymerElements/paper-toast#82]
A toast message with text + an animated SVG would be an awesome progess indicator !!

**Comment by valdrinkoshi** [comment]
You could insert any other element into the `paper-toast` instead of using the `text` property, like this http://jsbin.com/hezuta/1/edit?html,output

**Comment by triune** [comment]
Wow! That is a brilliant solution! I guess there's no need for my feature request then.

Cheers @valdrinkoshi  !!

**Comment by valdrinkoshi** [comment]
np 👍 
Closing this
