### ISSUE TITLE
noCancelOnOutsideClick is false but still not closes the toast on clicking on 'paper-tabs' area

### ISSUE THREAD

**Issue by vidyashreen1991** [PolymerElements/paper-toast#91]

**Comment by valdrinkoshi** [comment]
Confirmed http://jsbin.com/yelaza/3/edit?html,output
Looks related to https://github.com/PolymerElements/iron-overlay-behavior/issues/225, `IronOverlayManager` should have `useCapture = true` for the `tap` events

**Comment by valdrinkoshi** [comment]
fixed in iron-overlay-behavior v1.10.3
