### ISSUE TITLE
this element doesn't appear in any collection webcomponents.org

### ISSUE THREAD

**Issue by akc42** [PolymerElements/paper-toast#93]
I got redirected to web components.org from the old catalog, and I expected to find this element in the paper-ui elements collection, but it wasn't there.

In the end I did a search to find it and it didn't appear to be in any of the paper collections.

**Comment by valdrinkoshi** [comment]
@samuelli how to include `paper-toast` in any of the paper-* collections?

**Comment by samuelli** [comment]
@valdrinkoshi: just update the corresponding repos bower.json. eg. https://github.com/PolymerElements/paper-elements/blob/master/bower.json

**Comment by valdrinkoshi** [comment]
Ok, I guess we should be adding paper-toast to https://github.com/PolymerElements/paper-overlay-elements

**Comment by valdrinkoshi** [comment]
moved to https://github.com/PolymerElements/paper-overlay-elements/issues/2
