### ISSUE TITLE
calling hide() function on paper-toast loses focus on paper-input inside paper-dialog

### ISSUE THREAD

**Issue by wojinwomacka** [PolymerElements/paper-toast#97]
### Description

Whenever is `paper-toast` hidden from the view (function `hide` is called) and user has focus on `paper-input`  that is inside `paper-dialog` (and obviously `paper-dialog` is shown) , focus on that input is lost and immediately restored. This behavior makes text inside `paper-input` selected.

This is really annoying.. Imagine a situation, where the user writes something in `paper-input` and `paper-toast` will just dissapear. Well, everything the user has written will be lost, because he pressed some key when whole text was selected.

I tried to search for the cause and the only thing i found out was that is has something to do with `iron-overlay-behavior`.

I am using newest elements from master branch

### Expected outcome
Hiding `paper-toast` shouldn't lose focus on currently focused input inside `paper-dialog`

### Actual outcome
Whenever is `paper-toast` hide function called, the focus on element is lost and immediately restored, with whole text selected. (works only if is `paper-input` inside  `paper-dialog`)

### Steps to reproduce
1. Create `paper-toast` element, also create `paper-dialog` with `paper-input`  inside it (you can also try `paper-textarea`). 
2. On web, open `paper-dialog` and in console, try to open `paper-toast` with some duration (default is 3000 which is enough). 
3. Click on the `paper-input` to focus it just before the duration on `paper-toast` expires and wait until `paper-toast` will close. 

### Browsers Affected

- [x] Chrome
- [x] Firefox

**Comment by schlm3** [comment]
The title of the issue may be misleading, since the problem does not only happen when calling hide(), but simply every time the toast closes.

**Comment by iSuslov** [comment]
Same problem +1

**Comment by jasonsavard** [comment]
I found a workaround by adding no-auto-focus to your paper-dialog.

**Comment by valdrinkoshi** [comment]
This looks like a bug on iron-overlay-behavior, here a simpler repro: http://output.jsbin.com/donaqan/1
