### ISSUE TITLE
On-tap doesn't work on mobile

### ISSUE THREAD

**Issue by kownacki** [PolymerElements/paper-toast#98]
On-tap on `paper-toast` doesn't work on mobile or on device mode on chrome dev tools.

**Comment by valdrinkoshi** [comment]
This seems to be working fine 
demo: http://output.jsbin.com/sinolex/1/quiet
code: http://jsbin.com/sinolex/1/edit?html,output
![toast-on-tap](https://user-images.githubusercontent.com/6173664/38206614-f07f4a02-365f-11e8-9034-9b2f55fd65f3.gif)
